spring:
  redis:
    host: 10.211.55.30
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 300ms
        min-idle: 0
    password: 123456